using UnityEngine;

public class OutlineHelper : MonoBehaviour
{
    public Material material;

    void Awake()
    {
        // Generate a new render texture for the player layer.
        RenderTexture rt = new RenderTexture(Screen.width, Screen.height, 8);
        rt.filterMode = FilterMode.Point;
        Debug.Assert(rt.Create(), "Failed to create texture.");

        // Assign the new, screen sized texture as the target texture of the player camera.
        Camera cam = GetComponent<Camera>();
        cam.targetTexture = rt;
        // Set material texture to the texture generated by this camera. This will then be processed by the shadergraph.
        material.SetTexture("_MainTex", rt);
    }
}
